// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repositories/interfaces.go

// Package repository_mocks is a generated GoMock package.
package repository_mocks

import (
	reflect "reflect"

	models "github.com/array/banking-api/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockWebhookNotificationRepositoryInterface is a mock of WebhookNotificationRepositoryInterface interface.
type MockWebhookNotificationRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookNotificationRepositoryInterfaceMockRecorder
}

// MockWebhookNotificationRepositoryInterfaceMockRecorder is the mock recorder for MockWebhookNotificationRepositoryInterface.
type MockWebhookNotificationRepositoryInterfaceMockRecorder struct {
	mock *MockWebhookNotificationRepositoryInterface
}

// NewMockWebhookNotificationRepositoryInterface creates a new mock instance.
func NewMockWebhookNotificationRepositoryInterface(ctrl *gomock.Controller) *MockWebhookNotificationRepositoryInterface {
	mock := &MockWebhookNotificationRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockWebhookNotificationRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookNotificationRepositoryInterface) EXPECT() *MockWebhookNotificationRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWebhookNotificationRepositoryInterface) Create(notification *models.WebhookNotification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWebhookNotificationRepositoryInterfaceMockRecorder) Create(notification interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWebhookNotificationRepositoryInterface)(nil).Create), notification)
}

// FindPending mocks base method.
func (m *MockWebhookNotificationRepositoryInterface) FindPending(limit int) ([]models.WebhookNotification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPending", limit)
	ret0, _ := ret[0].([]models.WebhookNotification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPending indicates an expected call of FindPending.
func (mr *MockWebhookNotificationRepositoryInterfaceMockRecorder) FindPending(limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPending", reflect.TypeOf((*MockWebhookNotificationRepositoryInterface)(nil).FindPending), limit)
}

// Update mocks base method.
func (m *MockWebhookNotificationRepositoryInterface) Update(notification *models.WebhookNotification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockWebhookNotificationRepositoryInterfaceMockRecorder) Update(notification interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWebhookNotificationRepositoryInterface)(nil).Update), notification)
}
