// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repositories/interfaces.go

// Package repository_mocks is a generated GoMock package.
package repository_mocks

import (
	reflect "reflect"

	models "github.com/array/banking-api/internal/models"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockExternalAccountRepositoryInterface is a mock of ExternalAccountRepositoryInterface interface.
type MockExternalAccountRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockExternalAccountRepositoryInterfaceMockRecorder
}

// MockExternalAccountRepositoryInterfaceMockRecorder is the mock recorder for MockExternalAccountRepositoryInterface.
type MockExternalAccountRepositoryInterfaceMockRecorder struct {
	mock *MockExternalAccountRepositoryInterface
}

// NewMockExternalAccountRepositoryInterface creates a new mock instance.
func NewMockExternalAccountRepositoryInterface(ctrl *gomock.Controller) *MockExternalAccountRepositoryInterface {
	mock := &MockExternalAccountRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockExternalAccountRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExternalAccountRepositoryInterface) EXPECT() *MockExternalAccountRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockExternalAccountRepositoryInterface) Create(account *models.ExternalAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", account)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockExternalAccountRepositoryInterfaceMockRecorder) Create(account interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockExternalAccountRepositoryInterface)(nil).Create), account)
}

// ListByUserID mocks base method.
func (m *MockExternalAccountRepositoryInterface) ListByUserID(userID uuid.UUID) ([]models.ExternalAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", userID)
	ret0, _ := ret[0].([]models.ExternalAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockExternalAccountRepositoryInterfaceMockRecorder) ListByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockExternalAccountRepositoryInterface)(nil).ListByUserID), userID)
}
