// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/interfaces.go

package service_mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockNorthwindClientInterface is a mock of NorthwindClientInterface interface.
type MockNorthwindClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNorthwindClientInterfaceMockRecorder
}

// MockNorthwindClientInterfaceMockRecorder is the mock recorder for MockNorthwindClientInterface.
type MockNorthwindClientInterfaceMockRecorder struct {
	mock *MockNorthwindClientInterface
}

// NewMockNorthwindClientInterface creates a new mock instance.
func NewMockNorthwindClientInterface(ctrl *gomock.Controller) *MockNorthwindClientInterface {
	mock := &MockNorthwindClientInterface{ctrl: ctrl}
	mock.recorder = &MockNorthwindClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNorthwindClientInterface) EXPECT() *MockNorthwindClientInterfaceMockRecorder {
	return m.recorder
}

// HealthCheck mocks base method.
func (m *MockNorthwindClientInterface) HealthCheck(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockNorthwindClientInterfaceMockRecorder) HealthCheck(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockNorthwindClientInterface)(nil).HealthCheck), ctx)
}
